server:
  port: 5500
spring:
  profiles: test
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
   console:
    enabled: true
    path: /console/
  rabbitmq:
    host: 192.168.99.101
    username: guest
    password: guest
spring.profiles.active: test
