spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test?useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
        ddl-auto: update

  rabbitmq:
      host: 192.168.99.100
      username: guest
      password: guest
---
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://mysql:3306/test?useSSL=false
      username: root
      password: root
  jpa:
      database: mysql
      hibernate:
          ddl-auto: update
  rabbitmq:
      host: rabbitmq
      username: guest
      password: guest
---
spring:
  profiles: swarm
  datasource:
      url: jdbc:mysql://${DB}:3306/test?useSSL=false
      username: root
      password: root
  jpa:
      database: mysql
      hibernate:
          ddl-auto: update
  rabbitmq:
      host: ${RABBIT}
      username: guest
      password: guest