server:
  port: 4500
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.99.101
      port: 27017
  rabbitmq:
    host: 192.168.99.101
    username: guest
    password: guest
---
spring:
  profiles: test
  data:
    mongodb:
      port: 27017