spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
   console:
    enabled: true
    path: /console/
server:
  port: 8000
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/test
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
        ddl-auto: update
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
        ddl-auto: update
---
spring:
  profiles: swarm
  datasource:
    url: jdbc:postgresql://${DB}:5432/test
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
        ddl-auto: update

  sleuth:
    sampler:
      percentage: 0.5

  zipkin:
    base-url: http://${ZIPKIN}:9411/
    enabled: true